### ISSUE TITLE
Seems weird to me that you can add events for the past

### ISSUE THREAD

**Issue by CodingCookieRookie** [CodingCookieRookie/ped#7]
![image.png](https://raw.githubusercontent.com/CodingCookieRookie/ped/main/files/35351436-098f-4cb2-970f-617b5c1ce8bf.png)

**Comment by LinkedInk** [comment]
Ah this is intentional, as part of a calendar. The intention is to eventually get the time displayed on the panel to say if a certain event has already happened and how many days in the past/future (or if its today) it is.

**Comment by CodingCookieRookie** [comment]
Hi @LinkedInk so sorry for the late reply I didn't check my e-mail haha. Sure no problem sorry about it!
